# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_client_patient_practice_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.CharField(db_column='APP_COMMENT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='opt_out',
            field=models.BooleanField(db_column='APP_OPT_OUT', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='outcome',
            field=models.CharField(db_column='APP_OUTCOME', null=True),
        ),
    ]
