# Generated by Django 4.2.7 on 2023-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_patient_comment_patient_opt_out_patient_outcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='patient',
            new_name='patients',
        ),
    ]
