# Generated by Django 4.2.7 on 2023-12-05 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_patient_client_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField()),
            ],
            options={
                'ordering': ('text',),
            },
        ),
    ]
