# Generated by Django 4.2.7 on 2023-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20231206_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='app_number',
            field=models.CharField(db_column='APP_NUMBER', max_length=10, null=True),
        ),
    ]
