# Generated by Django 4.2.8 on 2023-12-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_question_answer_answer_unique_practice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='outcome',
            field=models.CharField(db_column='APP_OUTCOME', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='APP_CREATED_AT', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='APP_UPDATED_AT', null=True)),
                ('odu_created_at', models.DateTimeField(db_column='ODU_CREATED_AT_UTC', null=True)),
                ('odu_updated_at', models.DateTimeField(db_column='ODU_UPDATED_AT_UTC', null=True)),
                ('extractor_created_at', models.DateTimeField(db_column='EXTRACTOR_CREATED_AT_UTC', null=True)),
                ('extractor_updated_at', models.DateTimeField(db_column='EXTRACTOR_UPDATED_AT_UTC', null=True)),
                ('extractor_removed_at', models.DateTimeField(db_column='EXTRACTOR_REMOVED_AT_UTC', null=True)),
                ('odu_id', models.CharField(db_column='APPOINTMENT_ODU_ID', max_length=255, primary_key=True, serialize=False)),
                ('client_pims_id', models.CharField(db_column='CLIENT_PIMS_ID', max_length=255, null=True)),
                ('patient_pims_id', models.CharField(db_column='PATIENT_PIMS_ID', max_length=255, null=True)),
                ('is_canceled_appointment', models.BooleanField(db_column='IS_CANCELED_APPOINTMENT', null=True)),
                ('resource_name', models.CharField(db_column='RESOURCE_NAME', max_length=255, null=True)),
                ('resource_odu_id', models.CharField(db_column='RESOURCE_ODU_ID', max_length=511, null=True)),
                ('resource_pims_id', models.CharField(db_column='RESOURCE_PIMS_ID', max_length=255, null=True)),
                ('division_odu_id', models.CharField(db_column='DIVISION_ODU_ID', max_length=255, null=True)),
                ('pims_source', models.CharField(db_column='PIMS_SOURCE', max_length=255, null=True)),
                ('pims_reason', models.CharField(db_column='PIMS_REASON', max_length=255, null=True)),
                ('pims_status', models.CharField(db_column='PIMS_STATUS', max_length=255, null=True)),
                ('pims_schedule_type', models.CharField(db_column='PIMS_SCHEDULE_TYPE', max_length=255, null=True)),
                ('date', models.DateField(db_column='APPOINTMENT_DATE', null=True)),
                ('datetime', models.DateTimeField(db_column='APPOINTMENT_DATETIME', null=True)),
                ('type', models.CharField(db_column='APPOINTMENT_TYPE', max_length=21, null=True)),
                ('notes', models.CharField(db_column='NOTES', max_length=255, null=True)),
                ('duration', models.BigIntegerField(db_column='DURATION', null=True)),
                ('client_odu_id', models.ForeignKey(db_column='CLIENT_ODU_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.client')),
                ('patient_odu_id', models.ForeignKey(db_column='PATIENT_ODU_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.patient')),
                ('practice_odu_id', models.ForeignKey(db_column='PRACTICE_ODU_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.practice')),
                ('server_odu_id', models.ForeignKey(db_column='SERVER_ODU_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
