# Generated by Django 4.2.8 on 2023-12-29 16:14

import apps.call_center.db.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_outcome_text_alter_patient_outcome_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=4000, verbose_name='Answer text'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='app_number',
            field=models.CharField(db_column='APP_NUMBER', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), apps.call_center.db.validators.validate_is_digit]),
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Activates sending SMS reminders to clients and sending changed data to the specified email.', verbose_name='Active')),
                ('senders_phone', models.CharField(blank=True, help_text='Can only contain 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10), apps.call_center.db.validators.validate_is_digit], verbose_name="Sender's phone number")),
                ('sms_scheduler', models.CharField(blank=True, max_length=100, verbose_name='Scheduler name in SMS')),
                ('sms_practice_name', models.CharField(blank=True, max_length=100, verbose_name='Practice name in SMS')),
                ('sms_phone', models.CharField(blank=True, help_text='Not currently in use.', max_length=20, verbose_name='Phone number in SMS')),
                ('sms_link', models.CharField(blank=True, max_length=100, verbose_name='Link in SMS')),
                ('email', models.EmailField(blank=True, help_text='Address to which password-protected archives with updated data will be sent.', max_length=254)),
                ('practice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='apps.practice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='practicesettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('senders_phone', ''), ('sms_scheduler', ''), ('sms_practice_name', ''), ('sms_link', ''), _connector='OR'), ('is_active', False)), models.Q(models.Q(('senders_phone', ''), _negated=True), models.Q(('sms_scheduler', ''), _negated=True), models.Q(('sms_practice_name', ''), _negated=True), models.Q(('sms_link', ''), _negated=True), models.Q(('is_active', False), ('is_active', True), _connector='OR')), _connector='OR'), name='check_fields_condition', violation_error_message='It is not allowed to make practice active if at least one of the fields is empty, and to save empty values if practice is active.'),
        ),
    ]
