# Generated by Django 4.2.8 on 2024-01-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_answer_text_alter_phone_app_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client_odu_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_odu_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='practice_odu_id',
            new_name='practice',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='server_odu_id',
            new_name='server',
        ),
    ]
