# Generated by Django 4.2.8 on 2024-01-09 14:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_rename_client_odu_id_appointment_client_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(django.db.models.functions.text.Upper('first_name'), name='upper_first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(django.db.models.functions.text.Upper('last_name'), name='upper_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(django.db.models.functions.text.Upper('full_name'), name='upper_full_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(django.db.models.functions.text.Upper('odu_id'), name='upper_odu_id_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(django.db.models.functions.text.Upper('address'), models.F('is_primary'), models.F('extractor_removed_at'), name='filter_by_email_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['app_number', 'is_primary', 'extractor_removed_at'], name='filter_by_phone_idx'),
        ),
    ]
