# Generated by Django 4.2.8 on 2024-01-15 08:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_client_upper_first_name_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=32)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='upper_first_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='upper_last_name_idx',
        ),
        migrations.AddIndex(
            model_name='smsevent',
            index=models.Index(fields=['send_at', 'status'], name='send_at_status_idx'),
        ),
    ]
