# Generated by Django 4.2.8 on 2024-01-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_smsevent_remove_client_upper_first_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(db_column='NOTES', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pims_reason',
            field=models.TextField(db_column='PIMS_REASON', null=True),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='sms_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Link in SMS'),
        ),
    ]
