# Generated by Django 4.2.8 on 2024-01-15 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_smsevent_remove_client_upper_first_name_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSHistoryEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_context', models.JSONField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='PENDING', max_length=32)),
                ('response', models.JSONField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.practice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
