# Generated by Django 4.2.8 on 2024-01-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_appointment_notes_and_more'),
        ('apps', '0014_smshistoryevent'),
    ]

    operations = [
    ]
