# Generated by Django 4.2.8 on 2024-01-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_merge_20240116_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pims_is_deleted',
        ),
        migrations.AddField(
            model_name='patient',
            name='pims_is_deleted',
            field=models.BooleanField(db_column='PIMS_IS_DELETED', null=True),
        ),
        migrations.AlterField(
            model_name='smshistoryevent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.client'),
        ),
        migrations.AlterField(
            model_name='smshistoryevent',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.practice'),
        ),
    ]
