# Generated by Django 4.2.8 on 2024-01-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_patient_pims_is_deleted_and_more'),
        ('apps', '0016_create_practice_info'),
    ]

    operations = [
    ]
