# Generated by Django 4.2.8 on 2024-01-18 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_merge_20240117_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_context', models.JSONField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='PENDING', max_length=32)),
                ('response', models.JSONField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_history', to='apps.client')),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_history', to='apps.practice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='launch_date',
            field=models.DateField(blank=True, help_text='Date when the SMS aggregation logic will check reminders with date_due between 7 weeks and 3 years.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sms_status',
            field=models.CharField(choices=[('CHECKED', 'Checked and passed as redundant'), ('EVENT_CREATED', 'Created SMS Event'), ('NO_PHONE_NUMBER', 'Checked and passed due to missing phone number'), ('NO_ACTIVE_CLIENT', 'Checked and passed due to lack of active client'), ('EXCLUDED_PHONE_TYPE', 'Checked and passed as the phone type is in the list of excluded phone types')], db_column='APP_SMS_STATUS', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='SMSHistoryEvent',
        ),
        migrations.AddField(
            model_name='reminder',
            name='sms_history',
            field=models.ForeignKey(db_column='APP_SMS_HISTORY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='apps.smshistory'),
        ),
    ]
