# Generated by Django 4.2.8 on 2024-01-25 10:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_smshistory_practicesettings_launch_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFilesEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NO_FILES', 'No Files'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='PENDING', max_length=32)),
                ('error_message', models.TextField(null=True)),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.practice')),
            ],
            options={
                'indexes': [models.Index(fields=['sent_date'], name='sent_date_files_event_idx'), models.Index(fields=['status'], name='status_files_event_idx')],
            },
        ),
    ]
