# Generated by Django 4.2.8 on 2024-01-29 07:45

import django.core.validators
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_smshistory_practicesettings_launch_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practicesettings',
            name='check_fields_condition',
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='archive_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=9)])),
        ),
        migrations.AddConstraint(
            model_name='practicesettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('senders_phone', ''), ('sms_scheduler', ''), ('sms_practice_name', ''), ('sms_link', ''), ('email', ''), _connector='OR'), ('is_active', False)), models.Q(models.Q(('senders_phone', ''), _negated=True), models.Q(('sms_scheduler', ''), _negated=True), models.Q(('sms_practice_name', ''), _negated=True), models.Q(('sms_link', ''), _negated=True), models.Q(('email', ''), _negated=True), models.Q(('is_active', False), ('is_active', True), _connector='OR')), _connector='OR'), name='check_fields_condition', violation_error_message='It is not allowed to make practice active if at least one of the fields is empty, and to save empty values if practice is active.'),
        ),
    ]
