# Generated by Django 4.2.8 on 2024-01-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_notificationfilesevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationFilesEvent',
            new_name='UpdatesEmailEvent',
        ),
    ]
