# Generated by Django 4.2.8 on 2024-01-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_practicesettings_check_fields_condition_and_more'),
        ('apps', '0020_rename_notificationfilesevent_updatesemailevent'),
    ]

    operations = [
    ]
