# Generated by Django 4.2.8 on 2024-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_faq_initial_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='outcome_at',
            field=models.DateTimeField(db_column='APP_OUTCOME_AT', default=None, null=True),
        ),
    ]
