# Generated by Django 4.2.8 on 2024-02-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_patient_outcome_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sms_status',
            field=models.CharField(choices=[('CHECKED', 'Checked and passed as redundant'), ('EVENT_CREATED', 'Created SMS Event'), ('NO_PHONE_NUMBER', 'Checked and passed due to missing phone number'), ('NO_ACTIVE_CLIENT', 'Checked and passed due to lack of active client'), ('EXCLUDED_PHONE_TYPE', 'Checked and passed as the phone type is in the list of excluded phone types'), ('APPOINTMENT_EXISTS', 'There is an appointment with a date after the last date_due reminder.')], db_column='APP_SMS_STATUS', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['date_due'], name='date_due_idx'),
        ),
    ]
