# Generated by Django 4.2.8 on 2024-02-28 07:29

from django.db import migrations
from django.db import transaction


FAQ = {}  # removed to avoid duplicating data


@transaction.atomic()
def create_qa_for_practices(apps, schema_editor):
    Practice = apps.get_model("apps", "Practice")
    Answer = apps.get_model("apps", "Answer")
    Question = apps.get_model("apps", "Question")

    Answer.objects.all().delete()
    Question.objects.all().delete()

    for question, answers in FAQ.items():
        question = Question.objects.create(
            text=question
        )
        for practice_id, answer in answers:
            practice_exists = Practice.objects.filter(odu_id=practice_id).exists()
            if practice_exists:
                Answer.objects.create(
                    practice_id=practice_id,
                    question=question,
                    text=answer
                )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_reminder_sms_status_reminder_date_due_idx'),
    ]

    operations = [
        migrations.RunPython(
            code=create_qa_for_practices,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
