# Generated by Django 4.2.8 on 2024-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_faq_migration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practicesettings',
            name='check_fields_condition',
        ),
        migrations.RenameField(
            model_name='practicesettings',
            old_name='senders_phone',
            new_name='sms_senders_phone',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='is_email_updates_enabled',
            field=models.BooleanField(default=False, help_text='Activates sending archives with data updates.', verbose_name='Sending updates by email'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='is_sms_mailing_enabled',
            field=models.BooleanField(default=False, help_text='Activates sending SMS reminders to clients.', verbose_name='SMS Mailing'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sms_status',
            field=models.CharField(choices=[('CHECKED', 'Checked and passed as redundant'), ('EVENT_CREATED', 'Created SMS Event'), ('NO_PHONE', 'Checked and passed due to missing primary phone number'), ('NO_ACTIVE_CLIENT', 'Checked and passed due to lack of active client'), ('EXCLUDED_PHONE_TYPE', 'Checked and passed as the phone type is in the list of excluded phone types'), ('APPOINTMENT_EXISTS', 'There is an appointment with a date after the last date_due reminder.')], db_column='APP_SMS_STATUS', max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='practicesettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('sms_senders_phone', ''), ('sms_scheduler', ''), ('sms_practice_name', ''), ('sms_link', ''), _connector='OR'), ('is_sms_mailing_enabled', False)), models.Q(models.Q(('sms_senders_phone', ''), _negated=True), models.Q(('sms_scheduler', ''), _negated=True), models.Q(('sms_practice_name', ''), _negated=True), models.Q(('sms_link', ''), _negated=True), models.Q(('is_sms_mailing_enabled', False), ('is_sms_mailing_enabled', True), _connector='OR')), _connector='OR'), name='check_sms_fields_condition', violation_error_message='It is not allowed to activate SMS Mailing if at least one of the fields is empty.'),
        ),
        migrations.AddConstraint(
            model_name='practicesettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email', ''), ('is_email_updates_enabled', False)), models.Q(models.Q(('email', ''), _negated=True), models.Q(('is_email_updates_enabled', False), ('is_email_updates_enabled', True), _connector='OR')), _connector='OR'), name='check_email_fields_condition', violation_error_message='You cannot activate sending updates if the email field is empty.'),
        ),
    ]
