# Generated by Django 4.2.8 on 2024-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_remove_practicesettings_check_fields_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='smshistory',
            index=models.Index(fields=['sent_at'], name='sent_at_idx'),
        ),
    ]
