# Generated by Django 4.2.8 on 2024-03-06 09:13

from django.db import migrations


outcomes = [
    'Client requested Vetstoria link',
    'Client opted to call clinic to schedule',
    'Scheduler scheduled for client via Vetstoria',
    'Client declined - moved away from area',
    'Client declined - pet died',
    'Client declined - changed clinics',
    'Client declined - not compliant',
    'Attempted contact - invalid email & no access to phone number',
    'Attempted contact - invalid phone number & no access to email/no email on file',
    'Attempted contact - invalid email & phone number',
    'Client did not respond to initial SMS or follow up call',
    'Invalid phone number, sent email',
    'Client no longer has pet',
    'Suspended reminder',
    'Client declined - pet rehomed',
    'Client declined - went to different clinic but wants to return',
    'Did not contact - vaccine is on backorder',
    'Did not contact - duplicate reminder',
    'Attempted contact - left voicemail',
    'Contacted for email & not an overdue reminder',
    'Attempted contact - invalid phone number & client did not respond to email',
    'Did not contact - missing phone number & do not email',
    'Did not contact - missing phone number & missing email',
    'Did not contact - rescue animal',
    'Client already booked but PetDesk did not reflect this',
    'Attempted contact - client\'s VM is full, sent text',
    'Appointment booked',
    'Client hung up, sent text',
    'Did not contact - practice manager request',
    'Contacted via SMS for prevention',
    'Attempted contact - does not speak English, sent text',
    'Did not contact - Frozen',
]

def add_outcomes(apps, schema_editor):
    Outcome = apps.get_model('apps', 'Outcome')
    Outcome.objects.all().delete()
    Outcome.objects.bulk_create(
        [Outcome(text=text) for text in outcomes]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_smshistory_is_followed_smshistory_sent_at_idx'),
    ]

    operations = [
        migrations.RunPython(add_outcomes, reverse_code=migrations.RunPython.noop),
    ]
