# Generated by Django 4.2.8 on 2024-03-07 09:28

from django.db import migrations

PRACTICE_INFO_MAP = {
        "5489-vss": [
            "8502042553",
            "Makenzie",
            "Cat Clinic of Destin",
            "850-269-2287",
            "https://vet.lc/1l5ga0",
            "rflynn@heartlandvetpartners.com"
        ],
        "5040-vss": [
            "2057628657",
            "Makenzie",
            "Indian Hills Animal Clinic",
            "205-345-1231",
            "https://vet.lc/efp5tq",
            "vpearce@heartlandvetpartners.com"
        ],
        "4905-vss": [
            "4235603146",
            "Makenzie",
            "Kingsport Vet Hospital",
            "423-246-8561",
            "https://vet.lc/l8ogjv",
            "dhartley@heartlandvetpartners.com"
        ],
        "49397-vss": [
            "2814078786",
            "Makenzie",
            "Vet Clinic of Pearland",
            "281-258-4276",
            "https://vet.lc/geip2s",
            "Jdao@heartlandvetpartners.com"
        ],
        "4775-vss": [
            "2283640662",
            "Makenzie",
            "Northwood Hills Animal Hospital",
            "228-832-0125",
            "https://vet.lc/d5cgft",
            "wgardner@heartlandvetpartners.com"
        ],
        "8364-vss": [
            "9729282271",
            "Makenzie",
            "Allen Family Vet",
            "972-396-8387",
            "https://vet.lc/oc7n9i",
            "Heather.Coffman@heartlandvetpartners.com"
        ],
        "14208-vss": [
            "9033072872",
            "Makenzie",
            "Canyon Creek Family Vet",
            "903-893-0163",
            "https://vet.lc/6it5b1",
            "Lori.Moore@heartlandvetpartners.com"
        ],
        "4883-vss": [
            "2484533899",
            "Jess",
            "Advanced Vet Medical Center",
            "248-478-5400",
            "https://vet.lc/i0tvbe",
            "sgonsler@heartlandvetpartners.com"
        ],
        "14560-vss": [
            "6154920372",
            "Jess",
            "Bellshire Family Vet",
            "615-868-0845",
            "https://vet.lc/ecphm7",
            "elizabeth.recha@heartlandvetpartners.com"
        ],
        "2844-vss": [
            "7736768361",
            "Jess",
            "Broadway Animal Hospital",
            "773-262-5445",
            "https://vet.lc/ksrvkv",
            "sgood@heartlandvetpartners.com"
        ],
        "2833-vss": [
            "8479576538",
            "Jess",
            "GreenTree Animal Hospital",
            "847-680-6543",
            "https://vet.lc/te0a9i",
            "rtaipalus@heartlandvetpartners.com"
        ],
        "13206-vss": [
            "8284191286",
            "Jess",
            "Healthy Petz Family Vet",
            "828-437-4524",
            "https://vet.lc/o9ps8i",
            "kim.moran@heartlandvetpartners.com"
        ],
        "2907-vss": [
            "3862988478",
            "Jess",
            "Hilltop Family Vet",
            "386-462-3822",
            "https://vet.lc/5dje29",
            "shannon.beach@heartlandvetpartners.com"
        ],
        "5487-vss": [
            "4233254150",
            "Jess",
            "Monroe County Animal Hospital",
            "423-337-7432",
            "For Monroe County location click here : https://vet.lc/4uggne  For Tellico Plains location click here: https://vet.lc/h9b9b8",
            "ddomain@heartlandvetpartners.com"
        ],
        "13620-vss": [
            "3862988481",
            "Jess",
            "Ormond Beach Family Vet",
            "386-677-0507",
            "https://vet.lc/bu8frp",
            "megan.boda@heartlandvetpartners.com"
        ],
        "9092-vss": [
            "2147745475",
            "Jess",
            "Stonebridge Family Vet",
            "214-856-7005",
            "https://vet.lc/qmpc1b",
            "jessica.spader@heartlandvetpartners.com"
        ],
        "5476-vss": [
            "6012100875",
            "Jess",
            "Town and Country Animal Hospital",
            "601-261-3839",
            "https://vet.lc/mrrrkc",
            "d.miller@heartlandvetpartners.com"
        ],
        "5159-vss": [
            "8479439991",
            "Jess",
            "Vernon Hills Animal Hospital",
            "847-367-4070",
            "https://vet.lc/bf0l17",
            "jrice@heartlandvetpartners.com"
        ],
        "4495-vss": [
            "3364773663",
            "Nancy",
            "Abri Vet Hospital",
            "336-785-9228",
            "https://vet.lc/j7eqav",
            "msotelo@heartlandvetpartners.com"
        ],
        "3310-vss": [
            "7047480461",
            "Nancy",
            "All God's Creatures",
            "706-250-1861",
            "https://vet.lc/cov8kk",
            "erigby@heartlandvetpartners.com"
        ],
        "9166-vss": [
            "3365366249",
            "Nancy",
            "Animal Ark Vet Hospital",
            "336-835-1082",
            "https://vet.lc/8d6rg4",
            "cmarks@heartlandvetpartners.com "
        ],
        "7930-vss": [
            "8652243384",
            "Nancy",
            "Blount Vet Clinic",
            "865-983-4020",
            "https://vet.lc/ub7s42",
            "jcarter@heartlandvetpartners.com"
        ],
        "5399-vss": [
            "7048022953",
            "Nancy",
            "Carolinas Vet Care Clinic",
            "704-439-0600",
            "https://app.petdesk.com/request-appointment/carolinas-veterinary-care-clinic?placeGUID=ea4ec529-d816-4f40-b416-cc1ca32b0ec9",
            "xrobles@heartlandvetpartners.com"
        ],
        "3108-vss": [
            "8284818906",
            "Nancy",
            "Hendersonville Vet Hospital",
            "828-692-0561",
            "https://vet.lc/t8crq6",
            "ahamrick@heartlandvetpartners.com"
        ],
        "5600-vss": [
            "8039568349",
            "Nancy",
            "Hudson Vet Hospital",
            "803-905-9700",
            "https://vet.lc/5d8ee7",
            "kpierce@heartlandvetpartners.com"
        ],
        "3734-vss": [
            "8652243385",
            "Nancy",
            "Roane Vet Hospital",
            "865-882-6327",
            "https://vet.lc/n3keml",
            "cjarvis@heartlandvetpartners.com"
        ],
        "15145-vss": [
            "7048025634",
            "Nancy",
            "Spay Neuter Clinic of the Carolinas",
            "704-542-9997",
            "https://vet.lc/esl8nc",
            "tzawila@heartlandvetpartners.com"
        ],
        "3029-vss": [
            "4235603054",
            "Nancy",
            "Tellico Bay Animal Hospital",
            "423-884-3646",
            "https://vet.lc/9bmler",
            "slane@heartlandvetpartners.com"
        ],
        "6144-vss": [
            "7048392689",
            "Nancy",
            "The Pet Hospital",
            "704-629-5390",
            "https://vet.lc/fka3cu",
            "mrichardson@heartlndvetpartners.com"
        ],
        "3583-vss": [
            "6062176973",
            "Nancy",
            "Country Hills Vet Hospital",
            "606-886-3467",
            "https://vet.lc/nrtdts",
            "agoff@heartlandvetpartners.com"
        ],
        "3689-vss": [
            "8283829972",
            "Nancy",
            "Vet Specialties Hospital at the Lake",
            "828-478-3500",
            "https://vet.lc/fgi6s9",
            "jbrown@heartlandvetpartners.com"
        ],
        "3069-vss": [
            "6362181479",
            "Sierra",
            "Animal Medical Center of Troy",
            "636-462-4662",
            "https://vet.lc/g29go4",
            "swilmes@heartlandvetpartners.com"
        ],
        "3850-vss": [
            "8122211834",
            "Sierra",
            "Care Pets Animal Hospital",
            "812-246-6146",
            "https://vet.lc/p9mab0",
            "ttaylor@heartlandvetpartners.com"
        ],
        "4420-vss": [
            "4172609421",
            "Sierra",
            "Divine Vet Clinic",
            "417-581-6210",
            "https://vet.lc/v5k230",
            "ckonrad@heartlandvetpartners.com"
        ],
        "23268-vss": [
            "3035519316",
            "Sierra",
            "Foothills Animal Hospital",
            "303-988-0403",
            "https://vet.lc/8cotbr",
            "smcneil@heartlandvetpartners.com"
        ],
        "22-multi": [
            "9522543922",
            "Sierra",
            "Bush Lake Pet Hospital",
            "952-746-9296",
            "https://vet.lc/d4ftcd",
            "csorvari@heartlandvetpartners.com"
        ],
        "23-multi": [
            "9522830837",
            "Sierra",
            "France Avenue Pet Hospital",
            "952-746-9296",
            "https://vet.lc/ff4esa",
            "csorvari@heartlandvetpartners.com"
        ],
        "17262-vss": [
            "5013941856",
            "Sierra",
            "Greenbrier Animal Hospital",
            "501-679-7387",
            "http://vet.lc/46sgqn",
            "award@heartlandvetpartners.com"
        ],
        "5209-vss": [
            "5128857773",
            "Sierra",
            "Highland's Pet Medical Clinic",
            "512-476-1069",
            "https://vet.lc/i1celn",
            "nia.womack@heartlandvetpartners.com"
        ],
        "3037-vss": [
            "9132146496",
            "Sierra",
            "Mission Animal Clinic",
            "913-432-3341",
            "https://vet.lc/2vl4na",
            "gharvey@heartlandvetpartners.com"
        ],
        "6940-vss": [
            "6362181492",
            "Sierra",
            "My Vet Animal Clinic",
            "636-938-3239",
            "https://vet.lc/j16ia6",
            "jelder@heartlandvetpartners.com"
        ],
        "88-multi": [
            "9374008210",
            "Sierra",
            "Clayton Animal Hospital",
            "937-836-6969",
            "https://vet.lc/flg6tl",
            "shenderson@heartlandvetpartners.com"
        ],
        "87-multi": [
            "9374008206",
            "Sierra",
            "North Main Animal Clinic",
            "937-890-4744",
            "https://vet.lc/190par",
            "shenderson@heartlandvetpartners.com"
        ],
        "32282-vss": [
            "6412070787",
            "Sierra",
            "Ottumwa Family Animal Care",
            "641-682-2291",
            "https://vet.lc/07aoma",
            "dmcconnel@heartlandvetpartners.com"
        ],
        "6178-vss": [
            "9402484653",
            "Sierra",
            "A Caring Heart Vet Hospital",
            "940-855-0451",
            "https://vet.lc/7qulhr",
            "cabney@heartlandvetpartners.com"
        ],
        "31438-vss": [
            "3174632118",
            "Sierra",
            "Noble West Animal Hospital",
            "317-218-3731",
            "https://vet.lc/ist5p8",
            "kpugsley@heartlandvetpartners.com"
        ],
        "5439-vss": [
            "2253218384",
            "Lisa",
            "Bocage Animal Hospital",
            "225-928-7550",
            "https://vet.lc/f4r5d9",
            "lsmith@heartlandvetpartners.com"
        ],
        "15387-vss": [
            "2253218385",
            "Lisa",
            "Crossroads Animal Hospital",
            "225-261-6000",
            "https://vet.lc/bmhsp0",
            "achatelain@heartlandvetpartners.com"
        ],
        "15153-vss": [
            "9852895103",
            "Lisa",
            "Destrehan Animal Hospital",
            "985-764-0001",
            "https://vet.lc/m7oef8",
            "dustton@heartlandvetpartners.com"
        ],
        "28178-vss": [
            "2253218386",
            "Lisa",
            "Hood Vet Hospital",
            "225-791-2098",
            "https://vet.lc/u04f86",
            "adunn@heartlandvetpartners.com"
        ],
        "3313-vss": [
            "6202696048",
            "Lisa",
            "Independence Animal Hospital",
            "620-331-3740",
            "https://vet.lc/qcrnvd",
            "lmarchant@heartlandvetpartners.com"
        ],
        "3434-vss": [
            "9185031751",
            "Lisa",
            "McKinney Animal Hospital",
            "918-245-8508",
            "https://vet.lc/ul0ri8",
            "tthompson@heartlandvetpartnets.com"
        ],
        "3045-vss": [
            "9132146506",
            "Lisa",
            "Oakbrook Animal Hospital",
            "913-884-8778",
            "https://vet.lc/mf0c05",
            "ngriffiths@heartlandvetpartners.com"
        ],
        "5719-vss": [
            "2253218387",
            "Lisa",
            "O'Neal Lane Pet Hospital",
            "225-273-0579",
            "https://vet.lc/ad5qb2",
            "dterry@heartlandvetpartners.com"
        ],
        "3435-vss": [
            "9185031753",
            "Lisa",
            "South County Animal Clinic",
            "918-518-6200",
            "https://vet.lc/mncmel",
            "kchisum@heartlandvetpartners.com"
        ],
        "3413-vss": [
            "4052895629",
            "Lisa",
            "Swaim Serum Co",
            "405-236-8581",
            "https://vet.lc/acif33",
            "ceberhardt@heartlandvetpartners.com"
        ],
        "16353-vss": [
            "9852895105",
            "Lisa",
            "Tchefuncte Animal Hospital",
            "985-845-7484",
            "https://vet.lc/c3mh35",
            "msweitzer@heartlandvetpartners.com"
        ],
        "14156-vss": [
            "9852895116",
            "Lisa",
            "Vet Medical Center",
            "985-847-0591",
            "https://vet.lc/asaic7",
            "emarquez@heartlandvetpartners.com"
        ],
        "4971-vss": [
            "4322510028",
            "Meghann",
            "Animal Clinic and Hospital",
            "432-694-2537",
            "https://vet.lc/uq46si",
            "dhubbard@heartlanvetpartners.com"
        ],
        "31537-vss": [
            "2817150491",
            "Meghann",
            "True Companion Animal Hospital",
            "281-363-8708",
            "https://vet.lc/qjtqg9",
            "ksullivan@heartlandvetpartnes.com"
        ],
        "14561-vss": [
            "4074991101",
            "Meghann",
            "Avalon Family Vet",
            "407-275-3430",
            "https://vet.lc/c8mpir",
            "robert.hernandez@heartlandvetpartners.com"
        ],
        "2834-vss": [
            "3149129729",
            "Meghann",
            "St. Louis Vet Center",
            "314-773-6400",
            "https://vet.lc/nac9mh",
            "asolar@heartlandvetpartners.com"
        ],
        "39586-vss": [
            "5742407462",
            "Meghann",
            "Parrett Vet Clinic",
            "574-936-2353",
            "https://vet.lc/8691cu",
            "aanderson@heartlandvetpartners.com"
        ],
        "3886-vss": [
            "9852893456",
            "Meghann",
            "Best Friends Animal Hospital",
            "985-876-7722",
            "https://vet.lc/12tta7",
            "msander@heartlandvetpartners.com"
        ],
        "3977-vss": [
            "3192506954",
            "Makenzie",
            "Animal Clinic Inc",
            "319-337-2123",
            "https://vet.lc/mho8fq",
            "animalclinic408@gmail.com"
        ],
        "15684-vss": [
            "3192515409",
            "Makenzie",
            "Cat Clinic of Iowa City",
            "319-351-2252",
            "https://vet.lc/c4o7ti ",
            "nsimmons@heartlandvetpartner.com"
        ],
        "7279-vss": [
            "8063387513",
            "Makenzie",
            "Cooper Veterinary Clinic",
            "806-687-0687",
            "https://vet.lc/i9go0l",
            "khunton@heartlandvetpartners.com"
        ],
        "4241-vss": [
            "5128857773",
            "Jess",
            "Highland Square Family Vet",
            "863-647-1986",
            "https://vet.lc/4vf24m ",
            "megan.boda@heartlandvetpartners.com"
        ],
        "15328-vss": [
            "3175649351",
            "Jess",
            "Oaklandon Family Vet",
            "317-823-3464",
            "https://vet.lc/lla3j4",
            "cassi.naden@heartlandvetpartners.com"
        ],
        "82014-vss": [
            "3802268103",
            "Jess",
            "Suburban Animal Clinic",
            "614-276-5479",
            "https://vet.lc/vivng3",
            "v.wells@heartlandvetpartners.com"
        ],
        "53706-vss": [
            "8285197199",
            "Nancy",
            "Pinnacle Animal Hospital",
            "828-676-2332",
            "https://vet.lc/ldoj5r",
            "syeomans@heartlandvetpartners.com"
        ],
        "86449-vss": [
            "3372825738",
            "Lisa",
            "Village Veterinary Center (LA)",
            "337-856-7441",
            "https://vet.lc/3fg1ii",
            "dtoucheque@heartlandvetpartners.com"
        ],
        "63335-vss": [
            "9185031793",
            "Sierra",
            "Eastside Veterinay Hospital",
            "918-371-2439",
            "https://vet.lc/9ubnlm",
            "jackie@eastsidevet.biz"
        ],
        "16488-vss": [
            "3132842673",
            "Lisa",
            "Harper Woods Veterinary Hospital",
            "313-881-8061",
            "https://vet.lc/nam0ev",
            "abommarito@heartlandvetpartners.com"
        ],
        "3025-vss": [
            "8473066623",
            "Meghann",
            "All Paws Veterinary Clinic",
            "847-854-1526",
            "https://vet.lc/ogu1sl",
            "sbaker@heartlandvetpartners.com"
        ],
        "5826-vss": [
            "3035658910",
            "Meghann",
            "A Pet's Place Animal Hospital",
            "303-651-7322",
            "https://vet.lc/h2gnet",
            "lgibson@heartlandvetpartners.com"
        ],
        "71038-vss": [
            "9034810775",
            "Meghann",
            "South Platte Veterinary Hospital",
            "303-781-8387",
            "https://vet.lc/mdoeut",
            "slogan@heartlandvetpartners.com"
        ],
        "16151-vss": [
            "5072036290",
            "Nancy",
            "Summers Ridge Veterinary Hospital",
            "507-234-6929",
            "https://vet.lc/urmu0j",
            "rschultz@heartlandvetpartners.com"
        ]
    }


def add_practicesettings_info(apps, schema_editor):
    PracticeSettings = apps.get_model("apps", "PracticeSettings")
    Practice = apps.get_model("apps", "Practice")

    for practice_id, values in PRACTICE_INFO_MAP.items():
        practice_exists = Practice.objects.filter(odu_id=practice_id).exists()
        if practice_exists:
            PracticeSettings.objects.filter(practice_id=practice_id).delete()
            PracticeSettings.objects.create(
                practice_id=practice_id,
                sms_senders_phone=values[0],
                sms_scheduler=values[1],
                sms_practice_name=values[2],
                sms_phone=values[3],
                sms_link=values[4],
                email=values[5]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_remove_and_add_outcomes'),
    ]

    operations = [
        migrations.RunPython(
            code=add_practicesettings_info,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
