# Generated by Django 4.2.8 on 2024-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_auto_20240311_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesettings',
            name='rdo_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='rdo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='scheduler_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
