# Generated by Django 4.2.8 on 2024-03-12 08:46

from django.db import migrations

PRACTICE_INFO_MAP = {
    "5489-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Tina Cloud",
        "tcloud@heartlandvetpartners.com"
    ],
    "5040-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Tina Cloud",
        "tcloud@heartlandvetpartners.com"
    ],
    "4905-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Dr. Shawna Huston",
        "shuston@heartlandvetpartners.com"
    ],
    "49397-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "4775-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Tina Cloud",
        "tcloud@heartlandvetpartners.com"
    ],
    "8364-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "14208-vss": [
        "mcloud@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "4883-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Julie Berry",
        "julie.berry@heartlandvetpartners.com"
    ],
    "14560-vss": [
        "mcloud@heartlandvetpartners.com",
        "Alicia Kuebler",
        "alicia.kuebler@heartlandvetpartners.com"
    ],
    "2844-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Lolita Kinsey-Brown",
        "lkinsey-brown@heartlandvetpartners.com"
    ],
    "2833-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Christy Zach",
        "czach@heartlandvetpartners.com"
    ],
    "13206-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Angela Linvill",
        "alinvill@heartlandvetpartners.com"
    ],
    "2907-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Kenny Beauchamp",
        "kbeauchamp@heartlandvetpartners.com"
    ],
    "5487-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Emma Meddles",
        "emeddles@heartlandvetpartners.com"
    ],
    "13620-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Kenny Beauchamp",
        "kbeauchamp@heartlandvetpartners.com"
    ],
    "9092-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "5476-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Tina Cloud",
        "tcloud@heartlandvetpartners.com"
    ],
    "5159-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Christy Zach",
        "czach@heartlandvetpartners.com"
    ],
    "4495-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3310-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "9166-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "7930-vss": [
        "mcloud@heartlandvetpartners.com",
        "Emma Meddles",
        "emeddles@heartlandvetpartners.com"
    ],
    "5399-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3108-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "5600-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3734-vss": [
        "mcloud@heartlandvetpartners.com",
        "Emma Meddles",
        "emeddles@heartlandvetpartners.com"
    ],
    "15145-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3029-vss": [
        "nearley@heartlandvetpartners.com",
        "Emma Meddles",
        "emeddles@heartlandvetpartners.com"
    ],
    "6144-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3583-vss": [
        "nearley@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "3689-vss": [
        "swisely@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "3069-vss": [
        "swisely@heartlandvetpartners.com",
        "Claire Pickens",
        "cpickens@heartlandvetpartners.com"
    ],
    "3850-vss": [
        "swisely@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "4420-vss": [
        "swisely@heartlandvetpartners.com",
        "Mike Brady",
        "mbrady@heartlandvetpartners.com"
    ],
    "23268-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Mike Brady",
        "mbrady@heartlandvetpartners.com"
    ],
    "22-multi": [
        "swisely@heartlandvetpartners.com",
        "Kay Beacom-Stoller",
        "kstoller@heartlandvetpartners.com"
    ],
    "23-multi": [
        "swisely@heartlandvetpartners.com",
        "Kay Beacom-Stoller",
        "kstoller@heartlandvetpartners.com"
    ],
    "17262-vss": [
        "mcloud@heartlandvetpartners.com",
        "Dr. Daniel Boggs",
        "dboggs@heartlandvetpartners.com"
    ],
    "5209-vss": [
        "mcloud@heartlandvetpartners.com",
        "Debbie Simpson",
        "dsimpson@heartlandvetpartners.com"
    ],
    "3037-vss": [
        "mcloud@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "6940-vss": [
        "mcloud@heartlandvetpartners.com",
        "Mike Brady",
        "mbrady@heartlandvetpartners.com"
    ],
    "88-multi": [
        "swisely@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "87-multi": [
        "swisely@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "32282-vss": [
        "swisely@heartlandvetpartners.com",
        "Kim Earley",
        "kearley@heartlandvetpartners.com"
    ],
    "6178-vss": [
        "mcloud@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "31438-vss": [
        "swisely@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "5439-vss": [
        "mcloud@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "15387-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "15153-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "28178-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "3313-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "3434-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "3045-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Dr. Daniel Boggs",
        "dboggs@heartlandvetpartners.com"
    ],
    "5719-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "3435-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "3413-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "16353-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "14156-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "4971-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "31537-vss": [
        "mcloud@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "14561-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Kenny Beauchamp",
        "kbeauchamp@heartlandvetpartners.com"
    ],
    "2834-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Claire Pickens",
        "cpickens@heartlandvetpartners.com"
    ],
    "39586-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Mike Neuhoff",
        "mneuhoff@heartlandvetpartners.com"
    ],
    "3886-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "3977-vss": [
        "mcloud@heartlandvetpartners.com",
        "Kim Earley",
        "kearley@heartlandvetpartners.com"
    ],
    "15684-vss": [
        "mcloud@heartlandvetpartners.com",
        "Kim Earley",
        "kearley@heartlandvetpartners.com"
    ],
    "7279-vss": [
        "mcloud@heartlandvetpartners.com",
        "Renee Humphries",
        "rhumphries@heartlandvetpartners.com"
    ],
    "4241-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Kenny Beauchamp",
        "kbeauchamp@heartlandvetpartners.com"
    ],
    "15328-vss": [
        "jbugbee@heartlandvetpartners.com",
        "Alicia Kuebler",
        "alicia.kuebler@heartlandvetpartners.com"
    ],
    "82014-vss": [
        "jbugbee@heartlandvetpartners.com",
        "MaryAnn Martinez-Bosso",
        "mbosso@heartlandvetpartners.com"
    ],
    "53706-vss": [
        "nearley@heartlandvetpartners.com",
        "Nathan Harling",
        "nharling@heartlandvetpartners.com"
    ],
    "86449-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Sara McGlone",
        "smcglone@heartlandvetpartners.com"
    ],
    "63335-vss": [
        "swisely@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "16488-vss": [
        "lkoerber@heartlandvetpartners.com",
        "Christy Zach",
        "czach@heartlandvetpartners.com"
    ],
    "3025-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Lolita Kinsey-Brown",
        "lkinsey-brown@heartlandvetpartners.com"
    ],
    "5826-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "71038-vss": [
        "meghann.miller@heartlandvetpartners.com",
        "Michele Bouwman",
        "mbouwman@heartlandvetpartners.com"
    ],
    "16151-vss": [
        "nearley@heartlandvetpartners.com",
        "Kay Beacom-Stoller",
        "kstoller@heartlandvetpartners.com"
    ]
}


def add_extra_practicesettings_info(apps, schema_editor):
    PracticeSettings = apps.get_model("apps", "PracticeSettings")
    Practice = apps.get_model("apps", "Practice")

    for practice_id, values in PRACTICE_INFO_MAP.items():
        practice_settings = PracticeSettings.objects.filter(practice_id=practice_id).first()
        if practice_settings:
            practice_settings.scheduler_email = values[0]
            practice_settings.rdo_name = values[1]
            practice_settings.rdo_email = values[2]
            practice_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_practicesettings_rdo_email_practicesettings_rdo_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=add_extra_practicesettings_info,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
