# Generated by Django 4.2.8 on 2024-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_extra_info_for_practice_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.CharField(db_column='APP_COMMENT', max_length=1000, null=True),
        ),
    ]
