# Generated by Django 4.2.8 on 2024-03-21 07:19

from django.db import migrations

templates = {
    ('heartguard', 'tri-heart', 'interceptor', 'sentinel', 'revolution', 'advantage multi', 'frontline', 'advantage', 'advantix', 'seresto', 'bravecto', 'nexgard', 'simparica', 'vectra', 'drontal plus', 'panacur', 'dasuquin', 'cosequin', 'glycoflex', 'credelio', 'trifexis', 'capstar', 'dewormer', 'deworming', 'proheart',): 'Hi, this is {scheduler} from {practice_name}! {your_pets_capitalized} is overdue for important preventative medications. Give us a call at our main phone number {practice_phone_number} so we can discuss getting refills!',
    ('dental',): 'Hi, this is {scheduler} from {practice_name}! {your_pets_capitalized} is overdue for important dental services. Give us a call at our main phone number {practice_phone_number} on the schedule!',
    ('spay', 'neuter'): 'Hi, this is {scheduler} from {practice_name}! {your_pets_capitalized} is overdue for a spay or neuter. Give us a call at our main phone number {practice_phone_number} so we can get {your_pets_capitalized} on the schedule!',
    ('fecal',): 'Hi, this is {scheduler} from {practice_name}! {your_pets_capitalized} is overdue for important preventative services. But don\'t worry! You can drop off a fresh stool sample anytime for testing!',
}


def add_sms_templates(apps, schema_editor):
    SMSTemplate = apps.get_model('apps', 'SMSTemplate')
    for key_words, template in templates.items():
        SMSTemplate.objects.create(
            key_words=key_words,
            template=template,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_smstemplate'),
    ]

    operations = [
        migrations.RunPython(
            code=add_sms_templates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
