# Generated by Django 4.2.8 on 2024-03-28 11:13

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_add_sms_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'verbose_name': 'SMS template', 'verbose_name_plural': 'SMS templates'},
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='archive_password',
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Practice contact email'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='is_email_updates_enabled',
            field=models.BooleanField(default=False, help_text='Activates sending Excel files with data updates.', verbose_name='Sending updates by email'),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='sms_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number in SMS'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key_words',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
    ]
