# Generated by Django 4.2.8 on 2024-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_alter_smstemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='appointment_datetime',
        ),
        migrations.RemoveField(
            model_name='address',
            name='client_pims_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_pims_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_pims_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='resource_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='resource_pims_id',
        ),
        migrations.RemoveField(
            model_name='clientpatientrelationship',
            name='client_pims_id',
        ),
        migrations.RemoveField(
            model_name='clientpatientrelationship',
            name='patient_pims_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='client_pims_id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='client_pims_id',
        ),
        migrations.AddField(
            model_name='client',
            name='client_record_updated_at',
            field=models.DateTimeField(db_column='CLIENT_RECORD_UPDATED_AT_UTC', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_safe_contact',
            field=models.BooleanField(db_column='IS_SAFE_TO_CONTACT', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='latest_transaction_date',
            field=models.DateField(db_column='LATEST_TRANSACTION_DATE', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_date_updated_at',
            field=models.DateTimeField(db_column='IS_NEW_DATE_UPDATED_AT_UTC', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='latest_medical_service_date',
            field=models.DateField(db_column='LATEST_MEDICAL_SERVICE_DATE', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='new_date_updated_at',
            field=models.DateTimeField(db_column='IS_NEW_DATE_UPDATED_AT_UTC', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_new_date',
            field=models.DateField(db_column='PATIENT_IS_NEW_DATE', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_record_updated_at',
            field=models.DateTimeField(db_column='PATIENT_RECORD_UPDATED_AT_UTC', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='catalog_odu_id',
            field=models.CharField(db_column='CATALOG_ODU_ID', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(db_column='ADDRESS_1', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(db_column='ADDRESS_2', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='earliest_online_transaction_date',
            field=models.DateTimeField(db_column='EARLIEST_ONLINE_TRANSACTION_DATETIME', null=True),
        ),
        migrations.AlterField(
            model_name='clientpatientrelationship',
            name='is_primary',
            field=models.BooleanField(db_column='PIMS_IS_PRIMARY', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='code',
            field=models.CharField(db_column='CATALOG_CODE', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_due',
            field=models.DateField(db_column='DUE_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(db_column='TYPE', null=True),
        ),
    ]
