# Generated by Django 4.2.8 on 2024-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_rename_datetime_appointment_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_home_practice',
            field=models.BooleanField(db_column='IS_HOME_PRACTICE', null=True),
        ),
        migrations.AddField(
            model_name='clientpatientrelationship',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subserver',
            name='data_source',
            field=models.CharField(db_column='DATA_SOURCE', max_length=255, null=True),
        ),
    ]
