# Generated by Django 4.2.8 on 2024-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_address_data_source_appointment_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesettings',
            name='end_date_for_launch',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='start_date_for_launch',
            field=models.DateField(null=True),
        ),
    ]
