# Generated by Django 4.2.8 on 2024-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_practicesettings_end_date_for_launch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesettings',
            name='end_date_for_launch',
            field=models.DateField(blank=True, help_text='The date that the SMS aggregation logic will use when generating SMS, i.e. defines the left boundary of the date range.', null=True),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='start_date_for_launch',
            field=models.DateField(blank=True, help_text='The date that the SMS aggregation logic will use when generating SMS, i.e. defines the right boundary of the date range. If you set only this date for the left boundary, the default logic will be used (7 weeks ago).', null=True),
        ),
    ]
