# Generated by Django 4.2.8 on 2025-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_alter_practicesettings_end_date_for_launch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='is_archived',
            field=models.BooleanField(db_column='APP_IS_ARCHIVED', default=False),
        ),
    ]
